### ISSUE TITLE
Does not expansion tilde in ghq.root

### ISSUE THREAD

**Issue by rokoucha** [himanoa/mkrepo#1]
When I execute `mkrepo test` in `/home/atnanasi`, mkrepo will make `~` directory in `/home/atnanasi`

![image](https://user-images.githubusercontent.com/6058487/67620640-0fea7900-f844-11e9-90a2-e3769a93ed49.png)

My .gitconfig is
```ini
[user]
        name = Atnanasi

[ghq]
        root = ~/Projects

[mkrepo]
        service = github.com
```
and version of mkrepo is
```
Make project directory for ghq style. 0.0.1
```

**Comment by himanoa** [comment]
Thanks create issue. I'm fixing this problem now.
