### ISSUE TITLE
Works differently from ghq when multiple `ghq.root`s exist

### ISSUE THREAD

**Issue by qryxip** [himanoa/mkrepo#5]
`.gitconfig` can have "multiple values" like this.

```gitconfig
[key]
	value = aaa
	value = bbb
```

And `ghq` recognizes multiple `ghq.root`s.

> This variable can have multiple values. If so, the first one becomes primary one i.e. new repository clones are always created under it. You may want to specify "$GOPATH/src" as a secondary root (environment variables should be expanded.)

When multiple `ghq.root`s found, `ghq` uses the **first** one for `ghq get` and `ghq root`. `mkrepo` uses the **last** one instead. Or rather, `gitconfig` crate does not seem to recognize "multiple values" correctly.

**Comment by himanoa** [comment]
It seems necessary to change dependent libraries to solve this problem.
Also the parser that accepts multiple value of `git config --list --null` has to be created. because gitconfig crates has not been long maintenance.
I will create for it if I feel like it. Please wait for that.

**Comment by qryxip** [comment]
Why not use [`git2`](https://crates.io/crates/git2), which is a libgit2 binding and maintained by [rust-lang](https://github.com/rust-lang)? [It seems to easy to use](https://docs.rs/git2/0.10.1/git2/).

**Comment by himanoa** [comment]
Thanks. I try rewrite to use git2 crate.
